// client/app/room/[id]/send/SendFormCard.tsx
import { Send } from "lucide-react"
import { ChangeEvent, useState } from "react"

import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export default function SendFormCard({ onFileChange, onSendClick }: { onFileChange?: (e: ChangeEvent<HTMLInputElement>) => void, onSendClick?: () => void }) {
  const [InFile, setInFile] = useState<File | null>(null)
  const onChange = (e: ChangeEvent<HTMLInputElement>) => {
    setInFile(e.target.files && e.target.files[0])
    onFileChange && onFileChange(e)
  }

  const onClick = () => {
    onSendClick && onSendClick();
  }

  return (
    <>
      <CardHeader>
        <CardTitle>Send</CardTitle>
        <CardDescription>Select a file to send</CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <Input type="file" multiple={false} onChange={onChange} />
          {/*<Button className="w-full gap-1" onClick={onClick}>*/}
          <Button className="w-full gap-1" disabled={!InFile} onClick={onClick}>
          <Send className="mr-2 h-3 w-3" />Send
        </Button>
      </CardContent>
    </>
  )
}

// client/src/lib/components/room/send/SendFormCard.svelte
<script lang="ts">
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$components/ui/card';
	import { InputFile } from '$components/ui/input';
	import { Button } from '$components/ui/button';
	import { createEventDispatcher } from 'svelte';
	import { Send } from 'lucide-svelte';

	let files: FileList;

	const dispatch = createEventDispatcher<{ send: { files: FileList } }>();
	const handleSend = () => {
		dispatch('send', { files });
	};
</script>

<Card>
	<CardHeader>
		<CardTitle>Send</CardTitle>
		<CardDescription>Select a file to send</CardDescription>
	</CardHeader>
	<CardContent class="space-y-3">
		<InputFile bind:files />
		<Button class="w-full" on:click={handleSend} disabled={!files}>
			<Send class="mr-2 h-3.5 w-3.5" />Send
		</Button>
	</CardContent>
</Card>
